# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
# Description: comp.cmake config file.
#              Please don't modify this file directly, which is auto generated by hdt command.
# Author: hdt

set(COMP_DIR "/usr/local/lib/python3.8/dist-packages/hdt/extensions/hdt_cmc_c_cpp")

