/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_huawei_falcon_state_cache_FalconValueState */

#ifndef _Included_com_huawei_falcon_state_cache_FalconValueState
#define _Included_com_huawei_falcon_state_cache_FalconValueState
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_huawei_falcon_state_cache_FalconValueState
 * Method:    initFalconCache
 * Signature: (D)J
 */
JNIEXPORT jlong JNICALL Java_com_huawei_falcon_state_cache_FalconValueState_initFalconCache
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_huawei_falcon_state_cache_FalconValueState
 * Method:    destroyFalconCache
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_huawei_falcon_state_cache_FalconValueState_destroyFalconCache
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_huawei_falcon_state_cache_FalconValueState
 * Method:    get
 * Signature: (JJJJ[BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_huawei_falcon_state_cache_FalconValueState_get
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_huawei_falcon_state_cache_FalconValueState
 * Method:    put
 * Signature: (JJJJ[BII[BII)V
 */
JNIEXPORT void JNICALL Java_com_huawei_falcon_state_cache_FalconValueState_put
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jbyteArray, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     com_huawei_falcon_state_cache_FalconValueState
 * Method:    delete
 * Signature: (JJJJ[BII)V
 */
JNIEXPORT void JNICALL Java_com_huawei_falcon_state_cache_FalconValueState_delete
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_huawei_falcon_state_cache_FalconValueState
 * Method:    getCacheSizeLimit
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_huawei_falcon_state_cache_FalconValueState_getCacheSizeLimit
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_huawei_falcon_state_cache_FalconValueState
 * Method:    setCacheSizeLimit
 * Signature: (JJJJI)V
 */
JNIEXPORT void JNICALL Java_com_huawei_falcon_state_cache_FalconValueState_setCacheSizeLimit
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jint);

/*
 * Class:     com_huawei_falcon_state_cache_FalconValueState
 * Method:    flush
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_com_huawei_falcon_state_cache_FalconValueState_flush
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
