/*
* Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
* You can use this software according to the terms and conditions of the Mulan PSL v2.
* You may obtain a copy of Mulan PSL v2 at:
*          http://license.coscl.org.cn/MulanPSL2
* THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
* EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
* MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
* See the Mulan PSL v2 for more details.
*/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_huawei_ock_bss_metric_BoostNativeMetricImpl */

#ifndef _Included_com_huawei_ock_bss_metric_BoostNativeMetricImpl
#define _Included_com_huawei_ock_bss_metric_BoostNativeMetricImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_huawei_ock_bss_metric_BoostNativeMetricImpl
 * Method:    open
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_huawei_ock_bss_metric_BoostNativeMetricImpl_open
    (JNIEnv *, jclass, jint);

/*
 * Class:     com_huawei_ock_bss_metric_BoostNativeMetricImpl
 * Method:    getMetric
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_huawei_ock_bss_metric_BoostNativeMetricImpl_getMetric
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_huawei_ock_bss_metric_BoostNativeMetricImpl
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_huawei_ock_bss_metric_BoostNativeMetricImpl_close(JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
