/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_huawei_ock_bss_jni_AbstractNativeHandleReference */

#ifndef _Included_com_huawei_ock_bss_jni_AbstractNativeHandleReference
#define _Included_com_huawei_ock_bss_jni_AbstractNativeHandleReference
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_huawei_ock_bss_jni_AbstractNativeHandleReference
 * Method:    close
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_huawei_ock_bss_jni_AbstractNativeHandleReference_close(JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
