/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#include "bss_def.h"
/* Header for class com_huawei_ock_bss_table_AbstractKMapTable */

#ifndef _Included_com_huawei_ock_bss_table_AbstractKMapTable
#define _Included_com_huawei_ock_bss_table_AbstractKMapTable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_huawei_ock_bss_table_AbstractKMapTable
 * Method:    contains
 * Signature: (JI[BI[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_huawei_ock_bss_table_AbstractKMapTable_contains(JNIEnv *, jclass, jlong, jint,
                                                                                    jlong, jint, jlong, jint);
/*
 * Class:     com_huawei_ock_bss_table_AbstractKMapTable
 * Method:    get
 * Signature: (JI[BI[BI)[B
 */
JNIEXPORT jlong JNICALL Java_com_huawei_ock_bss_table_AbstractKMapTable_get(JNIEnv *, jclass, jlong, jint, jlong, jint,
                                                                            jlong, jint);

/*
 * Class:     com_huawei_ock_bss_table_AbstractKMapTable
 * Method:    add
 * Signature: (JI[BI[BI[BI)V
 */
JNIEXPORT void JNICALL Java_com_huawei_ock_bss_table_AbstractKMapTable_add(JNIEnv *, jclass, jlong, jint, jlong, jint,
                                                                           jlong, jint, jlong, jint);

/*
 * Class:     com_huawei_ock_bss_table_AbstractKMapTable
 * Method:    remove
 * Signature: (JI[BI[BI)V
 */
JNIEXPORT void JNICALL Java_com_huawei_ock_bss_table_AbstractKMapTable_remove(JNIEnv *, jclass, jlong, jint, jlong,
                                                                              jint, jlong, jint);

/*
 * Class:     com_huawei_ock_bss_table_AbstractKMapTable
 * Method:    remove
 * Signature: (JI[BI)V
 */
JNIEXPORT void JNICALL Java_com_huawei_ock_bss_table_AbstractKMapTable_removeAll(JNIEnv *, jclass, jlong, jint, jlong,
                                                                                 jint);

#ifdef __cplusplus
}
#endif
#endif
