/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_huawei_ock_bss_common_memory_DirectBuffer */

#ifndef Included_com_huawei_ock_bss_common_memory_DirectBuffer
#define Included_com_huawei_ock_bss_common_memory_DirectBuffer
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_huawei_ock_bss_common_memory_DirectBuffer
 * Method:    nativeGetDirectBufferData
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_huawei_ock_bss_common_memory_DirectBuffer_nativeGetDirectBufferData(JNIEnv *, jclass,
                                                                                                     jlong);

/*
 * Class:     com_huawei_ock_bss_common_memory_DirectBuffer
 * Method:    nativeGetDirectBufferLength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_huawei_ock_bss_common_memory_DirectBuffer_nativeGetDirectBufferLength(JNIEnv *, jclass,
                                                                                                      jlong);

/*
 * Class:     com_huawei_ock_bss_common_memory_DirectBuffer
 * Method:    nativeReleaseDirectBuffer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_huawei_ock_bss_common_memory_DirectBuffer_nativeReleaseDirectBuffer(JNIEnv *, jclass,
                                                                                                    jlong);

/*
 * Class:     com_huawei_ock_bss_common_memory_DirectBuffer
 * Method:    nativeAcquireDirectBuffer
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_huawei_ock_bss_common_memory_DirectBuffer_nativeAcquireDirectBuffer(JNIEnv *, jclass,
                                                                                                     jlong, jint);

/*
 * Class:     com_huawei_ock_bss_common_memory_DirectBuffer
 * Method:    nativeAllocDirectBuffer
 * Signature: (I)Ljava/io/DirectByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_huawei_ock_bss_common_memory_DirectBuffer_nativeAllocDirectBuffer(JNIEnv *, jclass,
    jint);


/*
 * Class:     com_huawei_ock_bss_common_memory_DirectBuffer
 * Method:    nativeFreeDirectBuffer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_huawei_ock_bss_common_memory_DirectBuffer_nativeFreeDirectBuffer(JNIEnv *, jclass,
                                                                                                   jlong);

#ifdef __cplusplus
}
#endif
#endif
