/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#include "bss_def.h"
/* Header for class com_huawei_ock_bss_table_KVTableImpl */

#ifndef _Included_com_huawei_ock_bss_table_KVTableImpl
#define _Included_com_huawei_ock_bss_table_KVTableImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_huawei_ock_bss_table_KVTableImpl
 * Method:    put
 * Signature: (JI[BI[BI)V
 */
JNIEXPORT void JNICALL Java_com_huawei_ock_bss_table_KVTableImpl_put(JNIEnv *, jclass, jlong, jint, jlong, jint, jlong,
                                                                     jint);

/*
 * Class:     com_huawei_ock_bss_table_KVTableImpl
 * Method:    get
 * Signature: (JI[BI)[B
 */
JNIEXPORT jlong JNICALL Java_com_huawei_ock_bss_table_KVTableImpl_get(JNIEnv *, jclass, jlong, jint, jlong, jint);

/*
 * Class:     com_huawei_ock_bss_table_KVTableImpl
 * Method:    contains
 * Signature: (JI[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_huawei_ock_bss_table_KVTableImpl_contains(JNIEnv *, jclass, jlong, jint, jlong,
                                                                              jint);

/*
 * Class:     com_huawei_ock_bss_table_KVTableImpl
 * Method:    remove
 * Signature: (JI[BI)V
 */
JNIEXPORT void JNICALL Java_com_huawei_ock_bss_table_KVTableImpl_remove(JNIEnv *, jclass, jlong, jint, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
