/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_huawei_ock_bss_common_Checkpoint */

#ifndef Included_com_huawei_ock_bss_common_Checkpoint
#define Included_com_huawei_ock_bss_common_Checkpoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_huawei_ock_bss_common_Checkpoint
 * Method:    newCheckpoint
 * Signature: (JJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_huawei_ock_bss_common_Checkpoint_newCheckpoint(JNIEnv *, jclass, jlong, jlong,
                                                                                jstring);

/*
 * Class:     com_huawei_ock_bss_common_Checkpoint
 * Method:    createCheckpoint
 * Signature: (J)V
 */
JNIEXPORT jboolean JNICALL Java_com_huawei_ock_bss_common_Checkpoint_createCheckpoint(JNIEnv *, jobject, jlong, jlong,
                                                                                      jboolean);

#ifdef __cplusplus
}
#endif
#endif
