/*
* Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_huawei_ock_bss_table_BoostPQTable */

#ifndef _Included_boost_ss_com_huawei_ock_bss_table_BoostPQTable
#define _Included_boost_ss_com_huawei_ock_bss_table_BoostPQTable

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_huawei_ock_bss_table_BoostPQTable
 * Method:    open
 * Signature: (Jjava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_com_huawei_ock_bss_table_BoostPQTable_open(JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_huawei_ock_bss_table_BoostPQTable
 * Method:    add
 * Signature: (J[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_huawei_ock_bss_table_BoostPQTable_add(JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     com_huawei_ock_bss_table_BoostPQTable
 * Method:    remove
 * Signature: (J[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_huawei_ock_bss_table_BoostPQTable_remove(JNIEnv *, jobject, jlong,
                jbyteArray, jint);
#ifdef __cplusplus
}
#endif
#endif