/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_huawei_ock_bss_common_BoostStateDB */

#ifndef _Included_com_huawei_ock_bss_common_BoostStateDB
#define _Included_com_huawei_ock_bss_common_BoostStateDB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_huawei_ock_bss_common_BoostStateDB
 * Method:    open
 * Signature: (Lcom/huawei/ock/bss/common/conf/BoostConfig;)J
 */
JNIEXPORT jlong JNICALL Java_com_huawei_ock_bss_common_BoostStateDB_open(JNIEnv *, jclass, jobject);

/*
 * Class:     com_huawei_ock_bss_common_BoostStateDB
 * Method:    restore
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT jboolean JNICALL Java_com_huawei_ock_bss_common_BoostStateDB_restore(JNIEnv *, jobject, jlong, jobject,
                                                                               jobject, jobject, jboolean, jboolean);

/*
 * Class:     com_huawei_ock_bss_common_BoostStateDB
 * Method:    notifyDBSnapshotAbort
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_huawei_ock_bss_common_BoostStateDB_notifyDBSnapshotAbort(JNIEnv *, jobject, jlong,
                                                                                         jlong);

/*
 * Class:     com_huawei_ock_bss_common_BoostStateDB
 * Method:    notifyDBSnapshotComplete
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_huawei_ock_bss_common_BoostStateDB_notifyDBSnapshotComplete(JNIEnv *, jobject, jlong,
                                                                                         jlong);

/*
 * Class:     com_huawei_ock_bss_common_BoostStateDB
 * Method:    newIterator
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_huawei_ock_bss_common_BoostStateDB_newIterator(JNIEnv *, jobject, jlong);

/*
 * Class:     com_huawei_ock_bss_common_BoostStateDB
 * Method:    changeHeapAvailableSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_huawei_ock_bss_common_BoostStateDB_changeHeapAvailableSize(JNIEnv *, jclass, jlong);

/*
 * Class:     com_huawei_ock_bss_common_BoostStateDB
 * Method:    registerBoostNativeMetric
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_huawei_ock_bss_common_BoostStateDB_registerBoostNativeMetric
    (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
