/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#include "kv_helper.h"
/* Header for class com_huawei_ock_bss_table_iterator_SubTableEntryIterator */

#ifndef _Included_com_huawei_ock_bss_table_iterator_SubTableEntryIterator
#define _Included_com_huawei_ock_bss_table_iterator_SubTableEntryIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_huawei_ock_bss_table_iterator_SubTableEntryIterator
 * Method:    open
 * Signature: (JI[BI)J
 */
JNIEXPORT jlong JNICALL Java_com_huawei_ock_bss_table_iterator_SubTableEntryIterator_open(JNIEnv *, jclass, jlong, jint,
                                                                                          jlong, jint);

/*
 * Class:     com_huawei_ock_bss_table_iterator_SubTableEntryIterator
 * Method:    hasNext
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_huawei_ock_bss_table_iterator_SubTableEntryIterator_hasNext(JNIEnv *, jclass,
                                                                                                jlong);

/*
 * Class:     com_huawei_ock_bss_table_iterator_SubTableEntryIterator
 * Method:    next
 * Signature: (J)[B
 */
JNIEXPORT jobject JNICALL Java_com_huawei_ock_bss_table_iterator_SubTableEntryIterator_next(JNIEnv *, jclass, jlong,
                                                                                            jobject);

JNIEXPORT jboolean JNICALL Java_com_huawei_ock_bss_table_iterator_SubTableEntryIterator_close(JNIEnv *env, jclass,
                                                                                              jlong jCloseable);

#ifdef __cplusplus
}
#endif
#endif
