/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_huawei_ock_bss_table_KListTableImpl */

#ifndef _Included_com_huawei_ock_bss_table_KListTableImpl
#define _Included_com_huawei_ock_bss_table_KListTableImpl
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_huawei_ock_bss_table_KListTableImpl
 * Method:    put
 * Signature: (JI[BI[BI)V
 */
JNIEXPORT void JNICALL Java_com_huawei_ock_bss_table_KListTableImpl_put(JNIEnv *, jclass, jlong, jint, jlong, jint,
                                                                        jlong, jint);

/*
 * Class:     com_huawei_ock_bss_table_KListTableImpl
 * Method:    get
 * Signature: (JI[BI)[B
 */
JNIEXPORT void JNICALL Java_com_huawei_ock_bss_table_KListTableImpl_get(JNIEnv *, jclass, jlong, jint, jlong, jint,
                                                                        jobject);

/*
 * Class:     com_huawei_ock_bss_table_KListTableImpl
 * Method:    contains
 * Signature: (JI[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_huawei_ock_bss_table_KListTableImpl_contains(JNIEnv *, jclass, jlong, jint, jlong,
                                                                                 jint);

/*
 * Class:     com_huawei_ock_bss_table_KListTableImpl
 * Method:    remove
 * Signature: (JI[BI)V
 */
JNIEXPORT void JNICALL Java_com_huawei_ock_bss_table_KListTableImpl_remove(JNIEnv *, jclass, jlong, jint, jlong, jint);

/*
 * Class:     com_huawei_ock_bss_table_KListTableImpl
 * Method:    add
 * Signature: (JI[BI[BI)V
 */
JNIEXPORT void JNICALL Java_com_huawei_ock_bss_table_KListTableImpl_add(JNIEnv *, jclass, jlong, jint, jlong, jint,
                                                                        jlong, jint);

/*
 * Class:     com_huawei_ock_bss_table_KListTableImpl
 * Method:    addAll
 * Signature: (JI[BI[BI)V
 */
JNIEXPORT void JNICALL Java_com_huawei_ock_bss_table_KListTableImpl_addAll(JNIEnv *, jclass, jlong, jint, jlong, jint,
                                                                           jlong, jint);
/*
 * Class:     com_huawei_ock_bss_table_KListTableImpl
 * Method:    releaseAllBuffer
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_huawei_ock_bss_table_KListTableImpl_releaseAllBuffer(JNIEnv *env, jclass, jlong, jint);

/*
 * Class:     com_huawei_ock_bss_table_KListTableImpl
 * Method:    addAll
 * Signature: (JLjava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_huawei_ock_bss_table_KListTableImpl_doNativeSectionRead(JNIEnv *env, jclass, jlong,
                                                                                           jobject);

#ifdef __cplusplus
}
#endif
#endif
