/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_huawei_ock_bss_table_AbstractTable */

#ifndef _Included_com_huawei_ock_bss_table_AbstractTable
#define _Included_com_huawei_ock_bss_table_AbstractTable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_huawei_ock_bss_table_AbstractTable
 * Method:    open
 * Signature: (JLjava/lang/String;Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_com_huawei_ock_bss_table_AbstractTable_open(JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_huawei_ock_bss_table_AbstractTable
 * Method:    updateTtl
 * Signature: (JLjava/lang/String;Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_huawei_ock_bss_table_AbstractTable_updateTtl(JNIEnv *, jclass, jlong, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
